// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// ⚠️ PROJETO LOVABLE - JÁ TEM TUDO FUNCIONANDO
const supabaseUrl = 'https://jibpvpqgplmahjhswiza.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppYnB2cHFncGxtYWhqaHN3aXphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1ODA0ODcsImV4cCI6MjA3NjE1NjQ4N30.raNfZtKkNUZBHiAA6yobri0YoWZt_Ioq10qMC9hfNrcr';

// LIMPAR DADOS ANTIGOS DO PROJETO DELETADO - VERSÃO AGRESSIVA
if (typeof window !== 'undefined') {
  try {
    console.log('🧹 [CLEANUP] Iniciando limpeza agressiva de dados antigos...');
    
    // Limpar TODAS as chaves do localStorage que contenham qualquer referência a projetos antigos
    const keysToRemove: string[] = [];
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key) {
        const keyLower = key.toLowerCase();
        if (
          keyLower.includes('zunuqaidxffuhwmvcwul') ||
          keyLower.includes('qbtqjrcfseqcfmcqlngr') ||
          keyLower.includes('gbtqjrcfseqcfmcqlngr') ||
          (keyLower.includes('supabase') && !keyLower.includes('jibpvpqgplmahjhswiza'))
        ) {
          keysToRemove.push(key);
        }
      }
    }
    
    if (keysToRemove.length > 0) {
      console.warn(`🗑️ [CLEANUP] Removendo ${keysToRemove.length} chave(s) antiga(s) do localStorage`);
      keysToRemove.forEach(key => {
        console.log('   - Removendo:', key);
        localStorage.removeItem(key);
      });
    }

    // Limpar sessionStorage também
    const sessionKeysToRemove: string[] = [];
    for (let i = 0; i < sessionStorage.length; i++) {
      const key = sessionStorage.key(i);
      if (key) {
        const keyLower = key.toLowerCase();
        if (
          keyLower.includes('zunuqaidxffuhwmvcwul') ||
          keyLower.includes('qbtqjrcfseqcfmcqlngr') ||
          keyLower.includes('gbtqjrcfseqcfmcqlngr') ||
          (keyLower.includes('supabase') && !keyLower.includes('jibpvpqgplmahjhswiza'))
        ) {
          sessionKeysToRemove.push(key);
        }
      }
    }
    
    if (sessionKeysToRemove.length > 0) {
      console.warn(`🗑️ [CLEANUP] Removendo ${sessionKeysToRemove.length} chave(s) antiga(s) do sessionStorage`);
      sessionKeysToRemove.forEach(key => {
        console.log('   - Removendo:', key);
        sessionStorage.removeItem(key);
      });
    }
    
    console.log('✅ [CLEANUP] Limpeza concluída');
  } catch (e) {
    console.error('❌ [CLEANUP] Erro ao limpar storage:', e);
  }
}

console.log('🔧 [SUPABASE CLIENT] Inicializando com URL:', supabaseUrl);

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  },
  global: {
    headers: {
      'x-client-info': 'amzofertas-web'
    }
  }
});

// Validação em runtime
if (typeof window !== 'undefined') {
  console.log('✅ [SUPABASE CLIENT] Cliente criado');
  console.log('📍 [SUPABASE CLIENT] URL atual:', supabase.supabaseUrl);
  
  // Verificar se está usando o projeto correto
  if (!supabase.supabaseUrl.includes('jibpvpqgplmahjhswiza')) {
    const erro = `🚨 URL INCORRETA: ${supabase.supabaseUrl}. Esperado: jibpvpqgplmahjhswiza`;
    console.error(erro);
    alert(erro);
    throw new Error(erro);
  }
}

// INTERCEPTOR: Corrige URLs antigas em requisições (FETCH + XMLHttpRequest) - VERSÃO ULTRA AGRESSIVA
if (typeof window !== 'undefined') {
  const OLD_PROJECT_IDS = ['qbtqjrcfseqcfmcqlngr', 'gbtqjrcfseqcfmcqlngr', 'zunuqaidxffuhwmvcwul'];
  
  function shouldCorrectUrl(url: string | null | undefined): boolean {
    if (!url) return false;
    const urlStr = url.toString().toLowerCase();
    return OLD_PROJECT_IDS.some(oldId => urlStr.includes(oldId.toLowerCase()));
  }
  
  function correctUrl(url: string): string {
    return url.replace(/https?:\/\/([^/]+)\.supabase\.co/gi, supabaseUrl);
  }
  
  // INTERCEPTAR FETCH - VERSÃO MELHORADA
  const originalFetch = window.fetch;
  window.fetch = async function(input: RequestInfo | URL, init?: RequestInit): Promise<Response> {
    try {
      let url: string | null = null;
      
      if (typeof input === 'string') {
        url = input;
      } else if (input instanceof URL) {
        url = input.toString();
      } else if (input && 'url' in input) {
        url = (input as Request).url;
      }
      
      if (shouldCorrectUrl(url)) {
        const correctedUrl = correctUrl(url!);
        console.error('🚨 [CLIENT-FETCH] URL ANTIGA DETECTADA! Corrigindo:');
        console.error('   ❌ Antiga:', url!.substring(0, 150));
        console.error('   ✅ Nova:', correctedUrl.substring(0, 150));
        
        // Recriar o input com a URL corrigida
        if (typeof input === 'string') {
          input = correctedUrl;
        } else if (input instanceof URL) {
          input = new URL(correctedUrl);
        } else if (input && 'url' in input) {
          input = new Request(correctedUrl, input);
        }
      }
    } catch (e) {
      console.error('❌ [CLIENT-FETCH] Erro no interceptor:', e);
    }
    
    return originalFetch.call(this, input, init);
  };
  
  // INTERCEPTAR XMLHttpRequest - VERSÃO MELHORADA
  const OriginalXHR = window.XMLHttpRequest;
  window.XMLHttpRequest = function() {
    const xhr = new OriginalXHR();
    const originalOpen = xhr.open;
    
    xhr.open = function(method: string, url: string | URL, ...args: any[]) {
      const urlStr = typeof url === 'string' ? url : url.toString();
      if (shouldCorrectUrl(urlStr)) {
        const correctedUrl = correctUrl(urlStr);
        console.error('🚨 [CLIENT-XHR] URL ANTIGA DETECTADA! Corrigindo:');
        console.error('   ❌ Antiga:', urlStr.substring(0, 150));
        console.error('   ✅ Nova:', correctedUrl.substring(0, 150));
        return originalOpen.call(this, method, correctedUrl, ...args);
      }
      return originalOpen.call(this, method, url, ...args);
    };
    
    return xhr;
  };
  
  console.log('✅ [CLIENT] Interceptores ULTRA AGRESSIVOS instalados - URLs antigas serão bloqueadas e corrigidas');
}
